apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: flask-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: karenopswerks/python-flaskapp:v1.8.f751b0f
        ports:
        - containerPort: 5000
